name: Publish (PR)

on:
    workflow_dispatch:
    pull_request:
        branches:
            - development
        paths:
            - 'src/**'
            - 'electron-builder*.yml'

jobs:
    wait-for-lint:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        permissions:
            checks: read
        steps:
            - name: Wait for Test workflow to complete
              uses: lewagon/wait-on-check-action@v1.4.1
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  check-name: 'lint'
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  wait-interval: 10
                  allowed-conclusions: success

    publish:
        needs: wait-for-lint
        if: always() && (needs.wait-for-lint.result == 'success' || needs.wait-for-lint.result == 'skipped')
      runs-on: macos-latest

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v6

            - name: Install Node and PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Install dependencies
              run: pnpm install

            - name: Build MacOS DMGs
              uses: nick-invision/retry@v3.0.2
              with:
                  timeout_minutes: 30
                  max_attempts: 3
                  retry_on: error
                  command: |
                      pnpm run build && pnpm exec electron-builder --mac dmg --publish never

            - name: Upload MacOS DMGs
              uses: actions/upload-artifact@v7
              with:
                  name: macos-dmgs
                  path: dist/*.dmg
